AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OpenFastTrace as a service

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: ${stage}
      Variables:
        stage: ${stage}
      MethodSettings: [{
        "LoggingLevel": "INFO",
        "MetricsEnabled": False,
        "DataTraceEnabled": False,
        "ResourcePath": "/*",
        "HttpMethod": "*",
        "ThrottlingBurstLimit": 2,
        "ThrottlingRateLimit": 1,
        "CachingEnabled": False,
        "CacheTtlInSeconds": 300,
        "CacheDataEncrypted": False
      }]
      EndpointConfiguration: REGIONAL
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST'"
        MaxAge: "'600'"
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: AWS::StackName
          description: |
            OpenFastTrace as a service
        paths:
          /trace:
            post:
              description: Trace requirements
              responses:
                default:
                  statusCode: 200
              x-amazon-apigateway-integration:
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TraceLambda.Arn}/invocations


  TraceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.itsallcode.openfasttrace.lambda.TraceLambda
      Runtime: java8
      Timeout: 30
      MemorySize: 3008 # 128
      CodeUri: ${CodeUri}
      Events:
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /trace
            Method: POST

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}
